### ISSUE TITLE
Issue pulling Registered ruleset

### ISSUE THREAD

**Issue by bpii** [shirkdog/pulledpork3#39]
After a few separate installations, it appears that PulledPork3 attempts to pull **https://snort.org/rules/snortrules-snapshot-3160.tar.gz?oinkcode-<hidden\>**; however, 3160 does not exist as a publicly-viewable ruleset on the website. 

It appears that we are up to snapshot 31110, though I cannot find where in PulledPork this information gets updated or designated. I can provide my config file if necessary. 

Thank you

**Comment by 3x3cut0r** [comment]
you can specify the version in your pulledpork.conf:
`snort_version = 3.1.11.0`

then the download will be successfull, but i got another error:
<pre>
root@vps:~# /usr/local/bin/pulledpork3/pulledpork.py -c /usr/local/etc/pulledpork3/pulledpork.conf

    https://github.com/shirkdog/pulledpork3
      _____ ____
     `----,\    )   PulledPork v3.0.0-BETA
      `--==\\  /    Lowcountry yellow mustard bbq sauce is the best bbq sauce. Fight me.
       `--==\\/
     .-~~~~-.Y|\\_  Copyright (C) 2021 Noah Dietrich, Colin Grady, Michael Shirk
  @_/        /  66\_  and the PulledPork Team!
    |    \   \   _(")
     \   /-| ||'--'   Rules give me wings!
      \_\  \_\\
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Loading configuration file:  /usr/local/etc/pulledpork3/pulledpork.conf
Processing Registered ruleset
Traceback (most recent call last):
  File "/usr/local/bin/pulledpork3/pulledpork.py", line 926, in <module>
    main()
  File "/usr/local/bin/pulledpork3/pulledpork.py", line 292, in main
    src_files = listdir(so_src_folder)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/PulledPork-2021.10.13-10.55.08/extracted_rulesets/snortrules-snapshot-31110/so_rules/precompiled/debian10-x64'
</pre>

**Comment by bpii** [comment]
To add on to this, my 'version' variable was set to '3.0.0-BETA' by default, which I'm assuming refers to the version of PulledPork itself. Perhaps the ability to update on behalf of Snort's version number hasn't been implemented on PP3 yet; however, the LightSpd ruleset doesn't change names, so your automation will still be in tact for the duration that your Snort version remains constant. At least this is how I understand the current state of this program.

**Comment by NDietrich** [comment]
So i'm tracking two errors in this chain. 
Regarding @3x3cut0r issue with the distro, it looks like the registered ruleset has changed the names and removed some distro support, the only supported distros are **centos-x64, debian-x64, fc-x64, opensuse-x64, ubuntu-x64**. i'll update the pp.conf for this.

for the other issue reported by @bpii : PP3 by default tries to pull the registered ruleset that matches the version of snort you have. by default, PP3 will run snort with the -V flag (version) and parse the output to determine the version of snort you're running, and then try to download the ruleset for that version specifically.  You can override this feature by explicitly specifying the version number in your pp.conf using the **snort_version** option.  Note that this is not the **CONFIGURATION_NUMBER** option in pp.conf which is 3.0.0-BETA, which is just to track the version of the pp.conf file (and is not used anywhere at this time).

We have no control over when Talos releases registered ruleset packages, and sometimes they don't immediately sync with newly released snort versions, so you may have the latest version of snort, but the registered ruleset may take a few days to be released.

Luckily there is a solution: use the LightSPD ruleset instead of the registered ruleset.  The neat thing about LightSPD is that there is one archive file that has rules for all the different versions of snort, and if your version of snort is too new, we automatically use the most recent version in the LightSPD archive, so you'll be good to go without these issues.

set your PP.conf as follows, and you should be good to go:
```
community_ruleset = false
registered_ruleset = false
LightSPD_ruleset = true
```
you still need your oinkcode and whatever other options you've set below, but this should resolve the issues you're having.

please let me know if this explains the problem, and if this solves your issue.
thanks
noah

**Comment by bbowlsbey** [comment]
So is there no downside to using LightSPD ruleset vs. the Registered rules?  

Is there a write up somewhere that would detail how to manually pull down the latest ruleset ?  (seems like there are lots of docs for splunk 2 on this topic, but not so many for Splunk3)

**Comment by NDietrich** [comment]
@bbowlsbey : there is no downside to using the LightSPD ruleset vs. the Registered rules, the features should be comparable.

Regarding your question about downloading the ruleset: I assume you're not just downloading, but installing as well, correct?  To manually download the ruleset, just navigate to snort.org/downloads, log in, and you can download the TGZ file for either the LightSPD ruleset, or the registered ruleset for your version of Snort.

to install those files, it's a little more complex (especially with the LightSPD ruleset), because they use .states files to enable/disable rules based on the policy you want.
